stages:
  - packer
  - docker
  - deploy-dev
  - deploy-test

variables:
  DOCKER_HOST: tcp://localhost:2375/
  IMAGE: proget-hz.lonsid.cn/masa-blazor/docs:0.2.$CI_PIPELINE_ID

packer:
  # image: proget-hz.lonsid.cn/masa-blazor/dotnet/sdk:6.0-forlinux
  #image: registry.cn-hangzhou.aliyuncs.com/masa/dotnet_sdk:6.0-nodejs14.17.6
  image: registry.cn-hangzhou.aliyuncs.com/masa/dotnet_sdk:6.0.100-preview.7-nodejs14.16.1
  stage: packer
  only:
    - develop
  script:
    - ls 
    - ls src/
    - node -v
    - dotnet --version
    - git clone -b develop http://gitlab-hz.lonsid.cn/MASA-Stack/Framework/BlazorComponent.git ./src/BlazorComponent
    - dotnet build src
    - dotnet pack src --include-symbols -p:PackageVersion=0.2.$CI_PIPELINE_ID
    - dotnet nuget push "**/*.symbols.nupkg" -k $nugetkey -s https://api.nuget.org/v3/index.json
  artifacts:
    expire_in: 1 day
    paths:
      - ./src/BlazorComponent
  retry: 2

docker:
  image: docker:17.05.0
  stage: docker
  only:
    - develop
  services:
    - name: proget-hz.lonsid.cn/masa-images/library/docker:17.05.01-dind
  script:
    - docker login -u gitlabci -p gitlabci http://proget-hz.lonsid.cn
    - docker build -t $IMAGE .
    - docker push $IMAGE
  retry: 2

deploy-dev:
  image: proget-hz.lonsid.cn/masa-images/library/kubectl:1.17.2-newack
  stage: deploy-dev
  only:
    - develop
  script:
    - kubectl set image deployment/masa-blazor-docs masa-blazor-docs=$IMAGE -n masa-blazor
  retry: 2
  
deploy-test:
  image: proget-hz.lonsid.cn/masa-images/library/kubectl:1.17.2-newack 
  stage: deploy-test
  only:
    - develop
  script:
    - kubectl set image deployment/masa-blazor-docs masa-blazor-docs=$IMAGE -n test-masa-blazor
  retry: 2
  when: manual
    